### ISSUE TITLE
Theme displays incorrectly when style settings plugin not enabled.

### ISSUE THREAD

**Issue by Morning-Ivy** [CyanVoxel/vauxhall-obsidian#1]
# Description
When selecting the theme with no other plugins (ie: a default vault) all items appear either as pitch black or transparent aside from the highlight color native to obsidian. This issue persists even when restarting, and is consistent between all vaults i have tried it on.

![image](https://github.com/CyanVoxel/vauxhall-obsidian/assets/74999268/f56855cf-2fa5-46c0-a4fb-0a6e64e6a60b)

***
# How to Reproduce
 1. Create a new vault
 2. Enable community plugins
 3. Enable Vauxhall from the theme browser 
 
 ***
 # Closing Notes
the theme works perfectly fine when the plugin 'style-settings' is enabled, and the only time this theme breaks is when the plugin is turned off or not installed.
Additionally it is decently difficult to switch off of the theme while the issue is happening, as all dialogue are pitch black.

![image](https://github.com/CyanVoxel/vauxhall-obsidian/assets/74999268/c3eafcb5-3bb4-4022-a7f0-95f9cd6a9672)

**Comment by CyanVoxel** [comment]
Thank you so much for bringing this up! I can't believe I didn't test to see if the theme still worked without the Style Settings plugin before publishing... Everything should be working as intended now!
