### ISSUE TITLE
Code Blocks Not Visible

### ISSUE THREAD

**Issue by BloodAkatsuki** [CyanVoxel/vauxhall-obsidian#2]
Description:
Hello,

I am using the current theme in Obsidian.md and have noticed that the code blocks are very distinguishable. However, in the Tokyo Night theme, the code blocks blend more seamlessly with the rest of the text, providing a smoother visual experience.

Request:
Could you please update the theme.css to make code blocks less distinguishable, similar to the Tokyo Night theme? The goal is to achieve a less noticeable distinction between code blocks and the surrounding text.

Tokyo Night Theme:
![grafik](https://github.com/CyanVoxel/vauxhall-obsidian/assets/139355360/1f55a32c-443c-42db-bda3-5ea91f87b66a)
Vauxhell Theme: 
![grafik](https://github.com/CyanVoxel/vauxhall-obsidian/assets/139355360/6d0af118-ce0b-43cb-946a-5295bf9e0812)

Thank you for considering this request. I believe it will enhance the visual consistency and readability of the theme.

Best regards,
BloodAkatsuki

**Comment by CyanVoxel** [comment]
Sure thing! I agree it could use some higher contrast.

**Comment by CyanVoxel** [comment]
Sorry for the delay on this! Contrast increased in 55de6c8b3d1dccda92196522ba7e446ffd5c02d7 for both dark and light modes:
![code_block_fix](https://github.com/user-attachments/assets/760a6ded-2530-4768-8b82-713be94035d8)
